### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by susanlovaglio** [learn-co-curriculum/swift-outlets-lab#3]
learn.co thinks there are tests in this lab but there aren't. a pull request is all that's needed.

**Comment by JimCampagno** [comment]
@susanlovaglio Thanks for finding this! All good now--learn looks for the Test Folder to determine whether or not a lab should be indicated as "Pass local tests". In order to fix that, we have to (on creation of the lab) either not check off the box to create test targets along with the main project or if it already contains a test target and UI tests, we remove em from Xcode and remove the folder. That will do the trick. You might then have to re-deploy the lab.

**Comment by susanlovaglio** [comment]
👍
